#!/usr/bin/env node
// ruka-setup.js
//
// Usage:
//   node ruka-setup.js [<unity-project-path>] [--local]
//   setup.bat           [<unity-project-path>] [--local]
//
// --local  Prompt for local Ruka repo root and use a file: URL instead of
//          the remote Git URL. Useful for testing before the repo is published.
//
// First run: cd SetUp && npm install

import { intro, outro, text, confirm, note, log, isCancel, cancel } from '@clack/prompts';
import { fileURLToPath } from 'url';
import fs   from 'fs';
import path from 'path';
import { spawnSync } from 'child_process';

// ─────────────────────────────────────────────────────────────
// CONFIG  ── ruka-setup.config.json (same directory as this script)
// ─────────────────────────────────────────────────────────────

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function loadConfig() {
  const configPath = path.join(__dirname, 'ruka-setup.config.json');
  if (!fs.existsSync(configPath))
    throw new Error(`配置文件不存在：${configPath}`);
  return JSON.parse(fs.readFileSync(configPath, 'utf8'));
}

const USE_LOCAL = process.argv.includes('--local');

// ─────────────────────────────────────────────────────────────
// TEMPLATES
// ─────────────────────────────────────────────────────────────

const NUGET_CONFIG = `\
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
  <disabledPackageSources />
  <packageSourceCredentials />
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
  <config>
    <add key="packageInstallLocation" value="InPackagesFolder" />
    <add key="repositoryPath" value="./Packages" />
    <add key="PackagesConfigDirectoryPath" value="." />
    <add key="slimRestore" value="false" />
    <add key="PreferNetStandardOverNetFramework" value="true" />
  </config>
</configuration>
`;

const NUGET_PACKAGE_JSON =
  `{ "name": "nuget-packages", "version": "1.0.0", "displayName": "NuGetPackages", "description": "NuGetPackages", "dependencies": {} }\n`;

// Full gitignore for fresh projects (based on github/gitignore Unity template)
const GITIGNORE_TEMPLATE = `\
# This .gitignore file should be placed at the root of your Unity project directory
#
# Get latest from https://github.com/github/gitignore/blob/main/Unity.gitignore
#
.utmp/
/[Ll]ibrary/
/[Tt]emp/
/[Oo]bj/
/[Bb]uild/
/[Bb]uilds/
/[Ll]ogs/
/[Uu]ser[Ss]ettings/
*.log

*.blend1
*.blend1.meta

/[Mm]emoryCaptures/
/[Rr]ecordings/

# Autogenerated Jetbrains Rider plugin
/[Aa]ssets/Plugins/Editor/JetBrains*
*.DotSettings.user

# Visual Studio
.vs/
.vsconfig
*.lscache

# Gradle
.gradle/

# Autogenerated VS/MD/Consulo solution and project files
ExportedObj/
.consulo/
*.csproj
*.unityproj
*.sln
*.slnx
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db

# Unity3D generated meta files
*.pidb.meta
*.pdb.meta
*.mdb.meta

# Unity3D crash reports
sysinfo.txt

# Mono
mono_crash.*

# Builds
*.apk
*.aab
*.unitypackage
*.unitypackage.meta
*.app

# Crashlytics
crashlytics-build.properties

# TestRunner
InitTestScene*.unity*

# Addressables
/ServerData
/[Aa]ssets/StreamingAssets/**
/[Aa]ssets/AddressableAssetsData/link.xml*
/[Aa]ssets/Addressables_Temp*
/[Aa]ssets/AddressableAssetsData/*/*.bin*

# Visual Scripting
/[Aa]ssets/Unity.VisualScripting.Generated/VisualScripting.Flow/UnitOptions.db
/[Aa]ssets/Unity.VisualScripting.Generated/VisualScripting.Flow/UnitOptions.db.meta
/[Aa]ssets/Unity.VisualScripting.Generated/VisualScripting.Core/Property Providers
/[Aa]ssets/Unity.VisualScripting.Generated/VisualScripting.Core/Property Providers.meta
/[Aa]ssets/[Ii]nit[Tt]est[Ss]cene*.unity*

# Local Tests
/[Aa]ssets/[Ll]ocalTests/
/[Aa]ssets/[Ll]ocalTests.meta

# macOS
.DS_Store
._*
.Spotlight-V100
.Trashes

# Ignore UPM resolved packages; track manifest and nuget config
/Packages/[^/]*/
!/Packages/manifest.json
!/Packages/packages-lock.json

# AI Agents
**.local.md
opencode.json
.opencode/
.agents/
.sisyphus/
.claude/
.codenomad/

# Plugins
/[Aa]ssets/Plugins.meta

# IDEs
.idea/
.vscode/

# LibreOffice locks
.~lock.*#

# YooAsset
/[Bb]undles/
/yoo/
/Sandbox/

# nuget-packages: track config, ignore installed DLLs
!/Packages/nuget-packages/
/Packages/nuget-packages/InstalledPackages/

# Ruka.Generated
/[Aa]ssets/Ruka.Generated/
/[Aa]ssets/Ruka.Generated.meta
`;

// Minimal addendum appended when a .gitignore already exists
const GITIGNORE_RUKA_ADDENDUM = `
# ── Ruka Setup ─────────────────────────────────────────────
# nuget-packages: track config, ignore installed DLLs
!/Packages/nuget-packages/
/Packages/nuget-packages/InstalledPackages/

# Ruka.Generated
/[Aa]ssets/Ruka.Generated/
/[Aa]ssets/Ruka.Generated.meta
# ──────────────────────────────────────────────────────────
`;

const RESTORE_BAT = `\
@echo off
setlocal

echo.
echo  Ruka ^— NuGet Restore
echo  ----------------------------------------
echo.

where dotnet >nul 2>&1
if %errorlevel% neq 0 (
    echo  [ERROR] dotnet CLI not found.
    echo  Install .NET 6 or later: https://dotnet.microsoft.com/download
    echo.
    pause
    exit /b 1
)

dotnet tool list -g | findstr /i "nugetforunity" >nul 2>&1
if %errorlevel% neq 0 (
    echo  Installing NuGetForUnity.Cli...
    dotnet tool install --global NuGetForUnity.Cli
    if %errorlevel% neq 0 (
        echo  [ERROR] Installation failed.
        pause
        exit /b 1
    )
)

nugetforunity restore "%~dp0"
if %errorlevel% neq 0 (
    echo  [ERROR] NuGet restore failed.
    pause
    exit /b 1
)

echo.
echo  Done.
pause
`;

// ─────────────────────────────────────────────────────────────
// VALIDATION
// ─────────────────────────────────────────────────────────────

function validateUnityProject(p) {
  const resolved = path.resolve(p.replace(/^["']|["']$/g, ''));
  if (!fs.existsSync(resolved))
    return `路径不存在：${resolved}`;
  const missing = ['Assets', 'ProjectSettings', 'Packages']
    .filter(d => !fs.existsSync(path.join(resolved, d)));
  if (missing.length)
    return `不是有效的 Unity 项目（缺少：${missing.join(', ')}）`;
  return undefined;
}

function validateRukaRepo(p) {
  const resolved = path.resolve(p.replace(/^["']|["']$/g, ''));
  if (!fs.existsSync(resolved))
    return `路径不存在：${resolved}`;
  if (!fs.existsSync(path.join(resolved, 'Assets', 'Ruka', 'package.json')))
    return `不是有效的 Ruka 仓库根目录（未找到 Assets/Ruka/package.json）`;
  return undefined;
}

function toUpmFileUrl(repoRoot) {
  const abs    = path.resolve(repoRoot.replace(/^["']|["']$/g, ''));
  const fwd    = abs.replace(/\\/g, '/');
  const prefix = fwd.startsWith('/') ? 'file:' : 'file:/';
  return `${prefix}${fwd}/Assets/Ruka`;
}

// ─────────────────────────────────────────────────────────────
// STATE  (checkpoint persistence)
// ─────────────────────────────────────────────────────────────

const STATE_FILENAME = '.ruka-setup-state.json';
const stateFilePath  = (p) => path.join(p, STATE_FILENAME);

function loadState(projectPath) {
  const f = stateFilePath(projectPath);
  return fs.existsSync(f) ? JSON.parse(fs.readFileSync(f, 'utf8')) : { phase: 0 };
}

function saveState(projectPath, state) {
  fs.writeFileSync(stateFilePath(projectPath), JSON.stringify(state, null, 2) + '\n', 'utf8');
}

function clearState(projectPath) {
  const f = stateFilePath(projectPath);
  if (fs.existsSync(f)) fs.unlinkSync(f);
}

// ─────────────────────────────────────────────────────────────
// MANIFEST.JSON HELPERS
// ─────────────────────────────────────────────────────────────

function readManifest(projectPath) {
  return JSON.parse(fs.readFileSync(path.join(projectPath, 'Packages', 'manifest.json'), 'utf8'));
}

function writeManifest(projectPath, manifest) {
  fs.writeFileSync(
    path.join(projectPath, 'Packages', 'manifest.json'),
    JSON.stringify(manifest, null, 2) + '\n',
    'utf8',
  );
}

function mergeRegistry(manifest, reg) {
  if (!manifest.scopedRegistries) manifest.scopedRegistries = [];
  let entry = manifest.scopedRegistries.find(r => r.url === reg.url);
  if (!entry) {
    entry = { name: reg.name, url: reg.url, scopes: [] };
    manifest.scopedRegistries.push(entry);
  }
  entry.scopes = [...new Set([...entry.scopes, ...reg.scopes])].sort();
}

function mergeUpmPackages(manifest, pkgs) {
  if (!manifest.dependencies) manifest.dependencies = {};
  const added = [], skipped = [];
  for (const [id, ver] of Object.entries(pkgs)) {
    if (manifest.dependencies[id] !== undefined) skipped.push(id);
    else { manifest.dependencies[id] = ver; added.push(id); }
  }
  return { added, skipped };
}

// ─────────────────────────────────────────────────────────────
// NUGET PACKAGES FOLDER  (InPackagesFolder mode)
// ─────────────────────────────────────────────────────────────

function setupNugetPackagesFolder(projectPath, nugetPkgs) {
  const nugetDir = path.join(projectPath, 'Packages', 'nuget-packages');
  fs.mkdirSync(nugetDir, { recursive: true });

  fs.writeFileSync(path.join(nugetDir, 'NuGet.config'),  NUGET_CONFIG,       'utf8');
  fs.writeFileSync(path.join(nugetDir, 'package.json'),  NUGET_PACKAGE_JSON, 'utf8');

  // packages.config — merge idempotently
  const configPath = path.join(nugetDir, 'packages.config');
  let content = fs.existsSync(configPath)
    ? fs.readFileSync(configPath, 'utf8')
    : '<?xml version="1.0" encoding="utf-8"?>\n<packages />';

  const existingIds = new Set([...content.matchAll(/id="([^"]+)"/g)].map(m => m[1]));
  const added = [], skipped = [], newLines = [];

  for (const pkg of nugetPkgs) {
    if (existingIds.has(pkg.id)) skipped.push(pkg.id);
    else {
      newLines.push(`  <package id="${pkg.id}" version="${pkg.version}" manuallyInstalled="true" />`);
      added.push(pkg.id);
    }
  }

  if (newLines.length) {
    content = content.replace(/<packages\s*\/>/g, '<packages>\n</packages>');
    content = content.replace('</packages>', newLines.join('\n') + '\n</packages>');
    fs.writeFileSync(configPath, content, 'utf8');
  }

  return { added, skipped };
}

// ─────────────────────────────────────────────────────────────
// GITIGNORE INJECTION
// ─────────────────────────────────────────────────────────────

function injectGitignore(projectPath) {
  const gitignorePath = path.join(projectPath, '.gitignore');

  if (!fs.existsSync(gitignorePath)) {
    fs.writeFileSync(gitignorePath, GITIGNORE_TEMPLATE, 'utf8');
    log.success('.gitignore 已写入');
    return;
  }

  const existing = fs.readFileSync(gitignorePath, 'utf8');
  if (existing.includes('nuget-packages')) {
    log.warn('.gitignore 已包含 nuget-packages 规则，跳过');
    return;
  }

  fs.writeFileSync(gitignorePath, existing.trimEnd() + '\n' + GITIGNORE_RUKA_ADDENDUM, 'utf8');
  log.success('.gitignore 已追加 Ruka 规则');
}

// ─────────────────────────────────────────────────────────────
// RESTORE SCRIPT  (for post-clone use)
// ─────────────────────────────────────────────────────────────

function writeRestoreScript(projectPath) {
  const batPath = path.join(projectPath, 'nuget-restore.bat');
  if (fs.existsSync(batPath)) {
    log.warn('nuget-restore.bat 已存在，跳过');
    return;
  }
  fs.writeFileSync(batPath, RESTORE_BAT, 'utf8');
  log.success('nuget-restore.bat 已写入（clone 后运行以恢复 NuGet DLL）');
}

// ─────────────────────────────────────────────────────────────
// UI HELPERS
// ─────────────────────────────────────────────────────────────

function reportChanges(added, skipped, label) {
  added.forEach(id   => log.success(`${label}: ${id}`));
  skipped.forEach(id => log.warn(`已存在跳过: ${id}`));
}

async function pauseForUnity(title, steps) {
  note(steps.map((s, i) => `${i + 1}. ${s}`).join('\n'), title);
  const response = await text({ message: '完成后按 Enter 继续', placeholder: '' });
  if (isCancel(response)) {
    cancel('已取消，进度已保存，重新运行可从断点继续。');
    process.exit(0);
  }
}

function guardCancel(value) {
  if (isCancel(value)) {
    cancel('已取消。');
    process.exit(0);
  }
  return value;
}

// ─────────────────────────────────────────────────────────────
// DOTNET / NUGETFORUNITY CLI
// ─────────────────────────────────────────────────────────────

function checkDotnet() {
  const r = spawnSync('dotnet', ['--version'], { encoding: 'utf8' });
  if (r.error || r.status !== 0) {
    cancel(
      '需要 .NET SDK（dotnet CLI）但未找到。\n' +
      '  请安装 .NET 6 或更高版本后重新运行：\n' +
      '  https://dotnet.microsoft.com/download',
    );
    process.exit(1);
  }
  log.info(`dotnet ${r.stdout.trim()}`);
}

function ensureNugetCli() {
  const list = spawnSync('dotnet', ['tool', 'list', '--global'], { encoding: 'utf8' });
  if ((list.stdout ?? '').toLowerCase().includes('nugetforunity')) {
    log.info('NuGetForUnity.Cli 已安装');
    return;
  }
  log.info('正在安装 NuGetForUnity.Cli（全局工具）...');
  const r = spawnSync(
    'dotnet', ['tool', 'install', '--global', 'NuGetForUnity.Cli'],
    { encoding: 'utf8', stdio: 'inherit' },
  );
  if (r.status !== 0) {
    cancel('NuGetForUnity.Cli 安装失败，请检查网络后重试。');
    process.exit(1);
  }
}

// Global .NET tools are installed to $HOME/.dotnet/tools/.
// If the tool was just installed in this session, PATH may not yet include
// that directory. Resolve the executable by absolute path as a fallback.
function resolveNugetForUnityExe() {
  const toolsDir = process.platform === 'win32'
    ? path.join(process.env.USERPROFILE ?? '', '.dotnet', 'tools')
    : path.join(process.env.HOME ?? '', '.dotnet', 'tools');
  const exe      = process.platform === 'win32' ? 'nugetforunity.exe' : 'nugetforunity';
  const fullPath = path.join(toolsDir, exe);
  return fs.existsSync(fullPath) ? fullPath : 'nugetforunity';
}

function runNugetRestore(projectPath) {
  log.info(`NuGet restore：${projectPath}`);
  const cmd = resolveNugetForUnityExe();
  const r   = spawnSync(cmd, ['restore', projectPath], { encoding: 'utf8', stdio: 'inherit' });
  if (r.error?.code === 'ENOENT') {
    cancel(
      'nugetforunity 命令未找到。\n' +
      '  请关闭此终端，重新打开后运行 setup.bat。',
    );
    process.exit(1);
  }
  if (r.status !== 0) {
    cancel('NuGet restore 失败，请查看上方输出。');
    process.exit(1);
  }
}

// ─────────────────────────────────────────────────────────────
// MAIN
// ─────────────────────────────────────────────────────────────

async function main() {
  const cfg = loadConfig();

  intro('Ruka Framework — 新项目配置向导');

  // ── Ruka source URL ──────────────────────────────────────
  let rukaUrl;
  if (USE_LOCAL) {
    log.info('模式：本地路径 (--local)');
    const rawRuka = guardCancel(await text({
      message: 'Ruka 仓库根目录路径',
      placeholder: 'C:/ProjectDev/Ruka',
      validate: validateRukaRepo,
    }));
    rukaUrl = toUpmFileUrl(rawRuka);
    log.success(`Ruka 本地路径：${rukaUrl}`);
  } else {
    rukaUrl = cfg.rukaRemoteUrl;
  }

  // ── Unity project path ───────────────────────────────────
  let rawPath = process.argv.find((a, i) => i >= 2 && !a.startsWith('--'));
  if (!rawPath) {
    rawPath = guardCancel(await text({
      message: 'Unity 项目根目录路径',
      placeholder: 'C:/Projects/MyGame',
      validate: validateUnityProject,
    }));
  } else {
    const err = validateUnityProject(rawPath);
    if (err) { cancel(err); process.exit(1); }
  }

  const projectPath = path.resolve(rawPath.replace(/^["']|["']$/g, ''));
  log.success(`Unity 项目：${projectPath}`);

  // ── Prerequisites ────────────────────────────────────────
  checkDotnet();
  ensureNugetCli();

  // ── Checkpoint ───────────────────────────────────────────
  let state = loadState(projectPath);
  if (state.phase > 0) {
    const resume = guardCancel(await confirm({
      message: '检测到上次进度（自动化阶段已完成），跳过直接进入 Unity 步骤？',
    }));
    if (!resume) state = { phase: 0 };
  }

  // ── Automated phase ──────────────────────────────────────
  try {
    if (state.phase < 1) {
      // Packages/nuget-packages/ + packages.config
      const { added: na, skipped: ns } = setupNugetPackagesFolder(projectPath, cfg.nugetPackages);
      reportChanges(na, ns, 'NuGet');

      // CLI restore → DLLs land before Unity opens
      runNugetRestore(projectPath);

      // manifest.json — all UPM packages in one shot
      const manifest = readManifest(projectPath);
      mergeRegistry(manifest, cfg.openupm);
      const { added: ua, skipped: us } = mergeUpmPackages(manifest, {
        ...cfg.upmPackages,
        'com.azane.ruka': rukaUrl,
      });
      writeManifest(projectPath, manifest);
      reportChanges(ua, us, 'UPM');

      // .gitignore + nuget-restore.bat
      injectGitignore(projectPath);
      writeRestoreScript(projectPath);

      saveState(projectPath, { phase: 1 });
    }
  } catch (err) {
    log.error(`意外错误：${err.message}`);
    log.warn('进度已保存，重新运行脚本可从断点继续。');
    process.exit(1);
  }

  // ── Single Unity step ────────────────────────────────────
  await pauseForUnity('请在 Unity 中完成最后一步', [
    '打开（或重新加载）Unity 项目',
    '等待所有 UPM 包下载并编译完成',
    '确认 Console 无报错',
  ]);

  clearState(projectPath);
  outro('Ruka 框架配置完成！');
}

main();
